<a href="https://colab.research.google.com/github/aaugustine130/AdvLinearAlgebra/blob/master/Math342_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
def location(a,b):
  """create a vector at location [a,b,1]"""
  return np.matrix([[a],[b], [1]])
def T(c,d):
  """Return a 3x3 matrix which translates x by a and y by b"""
  return np.matrix([[1,0,c], [0,1,d],[0,0,1]])

def R(phi):
  """Return a 3x3 matrix which translates around the origin by angle phi"""
  return np.matrix([[np.cos(np.deg2rad(phi)), -1*np.sin(np.deg2rad(phi)), 0], [np.sin(np.deg2rad(phi)), np.cos(np.deg2rad(phi)), 0], [0, 0, 1] ])

In [3]:
car_case_1a = location(3,0)
light_case_1a = location(3,1)
new_car_1a = T(3,0) * R(-90) * T(-3,0) * car_case_1a
new_car_1a

matrix([[3.],
        [0.],
        [1.]])

In [4]:
new_light_1a = T(3,0) * R(-90) * T(-3,0) * light_case_1a
new_light_1a

matrix([[4.],
        [0.],
        [1.]])

In [5]:
single_1a = T(3,0) * R(-90) * T(-3,0)
np.round(single_1a,0)

matrix([[ 0.,  1.,  3.],
        [-1.,  0.,  3.],
        [ 0.,  0.,  1.]])

In [6]:
point_1a = location(4,0)
new_point_1a = T(3,0) * R(-90) * T(-3,0) * point_1a
new_point_1a

matrix([[ 3.],
        [-1.],
        [ 1.]])

In [7]:
car_case_1b = location(3,2)
light_case_1b = location(3,3)
new_car_1b = T(3,2) * R(-90) * T(-3,-2) * car_case_1b
new_car_1b

matrix([[3.],
        [2.],
        [1.]])

In [8]:
new_light_1b = T(3,2) * R(-90) * T(-3,-2) * light_case_1b
new_light_1b

matrix([[4.],
        [2.],
        [1.]])

In [9]:
single_1b = T(3,2) * R(-90) * T(-3,-2)
np.round(single_1b,0)

matrix([[ 0.,  1.,  1.],
        [-1.,  0.,  5.],
        [ 0.,  0.,  1.]])

In [10]:
point_1b = location(4,2)
new_point_1b = T(3,2) * R(-90) * T(-3,-2) * point_1b
new_point_1b

matrix([[3.],
        [1.],
        [1.]])

In [11]:
car_case_2 = location(3,0)
light_case_2 = location(3,1)
new_car_case_2 = T(-2,-2) * R(180) * T(-3,0) * car_case_2
new_car_case_2

matrix([[-2.],
        [-2.],
        [ 1.]])

In [12]:
new_light_case_2 = T(-2,-2) * R(180) * T(-3,0) * light_case_2
new_light_case_2

matrix([[-2.],
        [-3.],
        [ 1.]])

In [13]:
single_case_2 = T(-2,-2) * R(180) * T(-3,0)
np.round(single_case_2,0)

matrix([[-1., -0.,  1.],
        [ 0., -1., -2.],
        [ 0.,  0.,  1.]])

In [17]:
def RabByPhi(a,b,phi, T, R):
  """Return a 3x3 matrix which rotates the car at location a,b by phi degrees."""
  return T(a,b) * R(phi) * T(-a, -b)

car_hw_3 = location(3,0)
light_hw_3 = location(3,1)
garage = T(0,1) * RabByPhi(-2,-3,90,T,R) * T(-2,0) * RabByPhi(0,-3,-90,T,R) * T(0,-3) * RabByPhi(0,0,90,T,R) * T(-3,0) * RabByPhi(3,0,90,T,R)
np.round(garage,0)

matrix([[-1., -0.,  1.],
        [ 0., -1., -2.],
        [ 0.,  0.,  1.]])

In [15]:
new_car_hw_3 = garage * car_hw_3
new_car_hw_3

matrix([[-2.],
        [-2.],
        [ 1.]])

In [16]:
new_light_hw_3 = garage * light_hw_3
new_light_hw_3

matrix([[-2.],
        [-3.],
        [ 1.]])